[package]
name = "t-systems-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
