FROM node:21 AS frontend-builder
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build -- --outDir dist

FROM caddy:latest

COPY Caddyfile /etc/caddy/Caddyfile

COPY --from=frontend-builder /app/frontend/dist /frontend/dist
